version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address ":9001" --console-address ":9000"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
